"""
config.py
----------------------------------
Central configuration module for the MMDS Project.
Handles environment variables, path setup, and runtime configuration
for both Spark and local Pandas-based workflows.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from typing import Optional

# Load .env from project root (if present)
load_dotenv()

# -------------------------------------------------------------------
# Base directories
# -------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent.parent
SRC_DIR = BASE_DIR / "src"
DATA_DIR = BASE_DIR / "data"
LOG_DIR = BASE_DIR / "logs"
DATA_DIR.mkdir(parents=True, exist_ok=True)
LOG_DIR.mkdir(parents=True, exist_ok=True)

# -------------------------------------------------------------------
# Database configuration (read from environment)
# -------------------------------------------------------------------
DB_NAME: Optional[str] = os.getenv("DB_NAME")
DB_USER: Optional[str] = os.getenv("DB_USER")
DB_PASS: Optional[str] = os.getenv("DB_PASS")
DB_HOST: Optional[str] = os.getenv("DB_HOST")
DB_PORT: Optional[str] = os.getenv("DB_PORT")

# Helper: minimal check for DB configuration completeness
def db_config_complete() -> bool:
    """Return True if the minimal DB environment variables are present."""
    return all([DB_NAME, DB_USER, DB_PASS, DB_HOST, DB_PORT])

# -------------------------------------------------------------------
# API / External credentials
# -------------------------------------------------------------------
REDDIT_CLIENT_ID: Optional[str] = os.getenv("REDDIT_CLIENT_ID")
REDDIT_CLIENT_SECRET: Optional[str] = os.getenv("REDDIT_CLIENT_SECRET")
REDDIT_USER_AGENT: Optional[str] = os.getenv("REDDIT_USER_AGENT")

# -------------------------------------------------------------------
# Data file paths
# -------------------------------------------------------------------
USERS_JSON_PATH = DATA_DIR / "users.json"
FOLLOWS_JSON_PATH = DATA_DIR / "follows.json"
POSTS_JSON_PATH = DATA_DIR / "posts.json"
EDGELIST_PATH = DATA_DIR / "follows.edgelist"

# -------------------------------------------------------------------
# Spark configuration
# -------------------------------------------------------------------
USE_SPARK_ETL: bool = os.getenv("USE_SPARK_ETL", "false").lower() == "true"
USE_SPARK_ANALYSIS: bool = os.getenv("USE_SPARK_ANALYSIS", "false").lower() == "true"
SPARK_MASTER: str = os.getenv("SPARK_MASTER", "local[*]")
SPARK_APP_NAME: str = os.getenv("SPARK_APP_NAME", "SocialMediaETL")
SPARK_ANALYSIS_TOPICS: int = int(os.getenv("SPARK_ANALYSIS_TOPICS", "20"))

# -------------------------------------------------------------------
# Live data analysis toggle
# -------------------------------------------------------------------
USE_LIVE_ANALYSIS: bool = os.getenv("USE_LIVE_ANALYSIS", "false").lower() == "true"

# -------------------------------------------------------------------
# Database table name constants (used across the project)
# -------------------------------------------------------------------
TABLE_USERS = "users"
TABLE_FOLLOWS = "follows"
TABLE_POSTS = "posts"
TABLE_GLOBAL_TOPICS = "global_topics"
TABLE_POST_TOPIC_MAPPING = "post_topic_mapping"
TABLE_LIVE_RESULTS = "live_results"

# -------------------------------------------------------------------
# Logging config helper
# -------------------------------------------------------------------
def get_log_file_path(filename: str = "mmds.log") -> Path:
    """
    Returns the full path for the primary project log file.
    Ensures the logs directory exists.
    """
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    return LOG_DIR / filename

# -------------------------------------------------------------------
# Misc helpers
# -------------------------------------------------------------------
def ensure_data_files_exist() -> None:
    """Create an empty data directory and touch expected files (no-op if present)."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    # don't create JSON files with content; keep them absent until generated by stages
